PATCH invalid JSON to nonexistent template id; expected 400 invalid_parameter before DB lookup
HTTP/1.1 400 Bad Request
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch
content-type: application/json
Date: Sun, 26 Apr 2026 10:31:14 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

{"error":{"type":"invalid_request_error","code":"invalid_parameter","message":"Invalid JSON body"}}